export default {
    user_id: '获得佣金的用户ID',
    channel_id: '渠道ID',
    channel__name: '渠道名字',
    source_user_id: '下级投注的用户ID',
    bet_amount: '投注金额',
    base_rate: '基础返佣比例,如 0.5',
    point_diff: '点位差',
    commission: '佣金金额',
    level: '距投注用户的层级',
    create_time: '创建时间',
    'quick Search Fields': 'id',
    // 错误消息
    'Team commission log cannot be added manually. It is automatically generated by the system.': '团队返佣记录不能手动添加，由系统自动生成。',
    'Team commission log cannot be modified.': '团队返佣记录不允许修改。',
    'Team commission log cannot be deleted.': '团队返佣记录不允许删除。',
}
