<?php

namespace app\admin\controller\team\commission;

use Throwable;
use app\common\controller\Backend;

/**
 * 团队佣金记录管理
 */
class Log extends Backend
{
    /**
     * Log模型对象
     * @var object
     * @phpstan-var \app\admin\model\team\commission\Log
     */
    protected object $model;

    protected array|string $preExcludeFields = ['id', 'create_time'];

    protected array $withJoinTable = ['channel'];

    protected string|array $quickSearchField = ['id'];

    public function initialize(): void
    {
        parent::initialize();
        $this->model = new \app\admin\model\team\commission\Log();
    }

    /**
     * 查看
     * @throws Throwable
     */
    public function index(): void
    {
        // 如果是 select 则转发到 select 方法，若未重写该方法，其实还是继续执行 index
        if ($this->request->param('select')) {
            $this->select();
        }

        /**
         * 1. withJoin 不可使用 alias 方法设置表别名，别名将自动使用关联模型名称（小写下划线命名规则）
         * 2. 以下的别名设置了主表别名，同时便于拼接查询参数等
         * 3. paginate 数据集可使用链式操作 each(function($item, $key) {}) 遍历处理
         */
        list($where, $alias, $limit, $order) = $this->queryBuilder();
        $res = $this->model
            ->withJoin($this->withJoinTable, $this->withJoinType)
            ->alias($alias)
            ->where($where)
            ->order($order)
            ->paginate($limit);
        $res->visible(['channel' => ['name']]);

        $this->success('', [
            'list'   => $res->items(),
            'total'  => $res->total(),
            'remark' => get_route_remark(),
        ]);
    }

    /**
     * 禁用添加功能 - 团队返佣记录由系统自动生成，不允许手动添加
     */
    public function add(): void
    {
        $this->error(__('Team commission log cannot be added manually. It is automatically generated by the system.'));
    }

    /**
     * 禁用编辑功能 - 团队返佣记录不允许修改
     */
    public function edit(): void
    {
        $this->error(__('Team commission log cannot be modified.'));
    }

    /**
     * 禁用删除功能 - 团队返佣记录不允许删除
     */
    public function del(): void
    {
        $this->error(__('Team commission log cannot be deleted.'));
    }

    /**
     * 禁用批量删除功能 - 团队返佣记录不允许删除
     */
    public function delIds(): void
    {
        $this->error(__('Team commission log cannot be deleted.'));
    }
}