export default {
    user_id: 'user_id',
    channel_id: 'channel_id',
    channel__name: 'name',
    source_user_id: 'source_user_id',
    bet_amount: 'bet_amount',
    base_rate: 'base_rate',
    point_diff: 'point_diff',
    commission: 'commission',
    level: 'level',
    create_time: 'create_time',
    'quick Search Fields': 'id',
    // Error messages
    'Team commission log cannot be added manually. It is automatically generated by the system.': 'Team commission log cannot be added manually. It is automatically generated by the system.',
    'Team commission log cannot be modified.': 'Team commission log cannot be modified.',
    'Team commission log cannot be deleted.': 'Team commission log cannot be deleted.',
}
