/** 可用的表格单元格渲染器，以 ./src/components/table/fieldRender/ 目录中的文件名自动生成 */
type TableRenderer =
    | 'buttons'
    | 'color'
    | 'customRender'
    | 'customTemplate'
    | 'datetime'
    | 'icon'
    | 'image'
    | 'images'
    | 'input'
    | 'switch'
    | 'tag'
    | 'tags'
    | 'timeInfo'
    | 'url'
    | 'slot'
